steps:
  - label: ":docker: build docker image"
    command: 
      - ".buildkite/steps/build-image.sh"
      - ".buildkite/steps/upload-image.sh"

  - wait

  - label: ":cop::skin-tone-2: unit-test check"
    command: ".buildkite/steps/unit-test.sh"
    timeout: 20

  - wait

  - label: ":cop::skin-tone-2: deploy check"
    command: ".buildkite/steps/deploy-test.sh -a"
    timeout: 20

  - wait

  - label: ":floppy_disk: publish image"
    command: ".buildkite/steps/publish-image.sh"
    branches: "master develop ci-* v*.*.*"

  - wait

  - label: ":slack:"
    command: ".buildkite/steps/slack.sh \"Pipeline complete successfully: ${BUILDKITE_MESSAGE}\" \"good\""
