version: "2.1"

services:
  mongo:
    container_name: mongo
    image: mongo:4.0.6-xenial
    restart: always
    healthcheck:
       test: mongo --eval 'db.getCollectionNames()'
       interval: 2s
       timeout: 2s
       retries: 10
    volumes:
      - cyberway-mongodb-data:/data/db
    ports:
      - 127.0.0.1:27018:27017

  notifier:
    container_name: notifier
    image: ${COMMUN_IMAGE}
    command: bash -c "until [ -S /queue/msg.sock ]; do sleep 1; done; exec /usr/bin/socat -u UNIX-CONNECT:/queue/msg.sock STDIO"
    volumes:
      - cyberway-queue:/queue:ro

  nodeosd:
    container_name: nodeosd
    image: cyberway/cyberway:${CW_TAG}
    depends_on:
      mongo:
        condition: service_healthy
      notifier:
        condition: service_started
    command: /opt/cyberway/bin/nodeosd.sh --data-dir /opt/cyberway/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --plugin eosio::event_engine_plugin --event-engine-unix-socket /queue/msg.sock --genesis-json /opt/cyberway/bin/genesis-data/genesis.json --genesis-data /opt/cyberway/bin/genesis-data/genesis.dat
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - cyberway-nodeos-data:/opt/cyberway/bin/data-dir
      - ${PWD}/config.ini:/opt/cyberway/bin/data-dir/config.ini
      - ${PWD}/genesis-data:/opt/cyberway/bin/genesis-data
      - cyberway-queue:/queue
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

volumes:
 cyberway-mongodb-data:
   external: true
 cyberway-nodeos-data:
   external: true
 cyberway-queue:
   external: true

networks:
  default:
    name: commun-deploy_test-net
